#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Customized add:"
  echo "    add pri PRIORITY \"THING I NEED TO DO +project @context\""
  echo "    add p PRIORITY \"THING I NEED TO DO +project @context\""
  echo "      add an item and prioritize it in one step"
  echo "    add x \"THING I NEEDED TO DO RIGHT NOW\""
  echo "      add an item and mark it as done in one step"
  echo ""
  exit
}

DO=false
if [ x"$1" = x"pri" -o x"$1" = x"p" ] && [[ x"$2" = x[a-zA-Z] ]]; then
    PRIORITY="($(echo $2 | tr [:lower:] [:upper:]))"
    shift
    shift
    item="$PRIORITY $@"
elif [ x"$1" = x"x" ]; then
    DO=true
    shift
    item="$@"
else
    item="$@"
fi


# apply common changes
if echo "$item" | grep -q @shopping && echo "$item" | grep -qv @errands; then
  item="$item @errands"
fi

# call back to the main script to add
if "$TODO_FULL_SH" command add $item; then
    # figure out the line of what we just added, and "do" it
    line=`sed -n '$ =' "$TODO_FILE"`
    $DO && "$TODO_FULL_SH" command do "$line"
fi

if echo "$item" | grep -q ':due '; then
    "$TODO_FULL_SH" daily >/dev/null 2>&1
fi
