#!/bin/bash

action="$1"
shift

# ignore usage prompts, since we're overriding a built-in in a way that doesn't
# change the usage
[ "$action" = "usage" ] && exit 0

# handle repeats
"$TODO_FULL_SH" command list x repeat | grep ^[0-9] | while read N X; do
  todo repeat "$N"
done

# call the built-in command to do most of the work
TODOTXT_VERBOSE=0 "$TODO_FULL_SH" command archive

# sort the done file into the temp file (removing duplicates), then replace the
# done file with the sorted version, but only if the sort doesn't fail
sort -u "$DONE_FILE" > "$TMP_FILE" && mv "$TMP_FILE" "$DONE_FILE"
