#!/bin/bash

shopt -s extglob

function die() {
  echo "$@"
  exit 1
}

function usage() {
  echo "    dupe NUMBER"
  echo "      Copies item on line NUMBER to a new item, then edits new item"
  echo
  exit
}

action="$1"
shift

[ "$action" = "usage" ] && usage

item="$1"

# validate item number: exists and is digit
[ -n "$item" ] || usage
[[ "$item" = +([0-9]) ]] || usage

# validate item number: corresponds to existing item
todo=$(sed "$item!d" "$TODO_FILE")
[ -z "$todo" ] && die "$item:  No such todo."

# add new item and edit it
"$TODO_FULL_SH" -d /dev/null add "$todo" &&
  vim +$(wc -l "$TODO_FILE") 
