#!/bin/bash

shopt -s extglob

function die() {
  echo "$@"
  exit 1
}

function usage() {
  echo "    edit NUMBER"
  echo "      Edits $TODO_FILE starting with item NUMBER"
  echo
  exit
}

action="$1"
shift

[ "$action" = "usage" ] && usage

item="$1"

# validate item number: exists and is digit
[ -n "$item" ] || usage
[[ "$item" = +([0-9]) ]] || usage

# validate item number: corresponds to existing item
todo=$(sed "$item!d" "$TODO_FILE")
[ -z "$todo" ] && die "$item:  No such todo."

# edit item
vim +"$item" "$TODO_FILE"
