#!/bin/bash

action="$1"
shift

[ "$action" = "usage" ] && exit 0

export TODOTXT_SORT_COMMAND="awk -f $TODO_ACTIONS_DIR/sort.awk"
export pre_filter_command="gawk --re-interval -f $TODO_ACTIONS_DIR/datefilter.awk"
# filter add dates
export post_filter_command="sed -e 's/\(^[0-9 ]\+ \(([A-Za-z]) \)\?\)[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} /\1/'"

_list "$TODO_FILE" "$@"
