#!/bin/bash

shopt -s extglob

function die() {
  echo "$@"
  exit 1
}

function usage() {
  echo "    priall PRIORITY ITEM# [ITEM#...]"
  echo "      Adds PRIORITY to all tasks given by ITEM#.  If any task is"
  echo "      already prioritized, replaces current priority with new PRIORITY."
  echo "      PRIORITY must be a letter between A and Z, or '-' to deprioritize."
  echo
  exit
}

action="$1"
shift

[ "$action" = "usage" ] && usage

priority="$1"
shift

# loop over items, adding priority to each
for item in "$@"; do
  if [ "$priority" = "-" ]; then
    "$TODO_FULL_SH" depri "$item" "$priority"
  else
    "$TODO_FULL_SH" pri "$item" "$priority"
  fi
done
