#!/bin/bash

shopt -s extglob

function die() {
  echo "$@"
  exit 1
}

function usage() {
  echo "    unpostpone"
  echo "      Unpostpone the last item."
  echo
  exit
}

action="$1"
shift

[ "$action" = "usage" ] && usage

item="$1"

# validate item number: exists and is digit
[ -n "$item" ] || usage
[[ "$item" = +([0-9]) ]] || usage

# validate item number: corresponds to existing item
todo=$(sed "$item!d" "$TODO_FILE")
[ -z "$todo" ] && die "$item:  No such todo."

# remove done marker and postpone marker
"$TODO_FULL_SH" regex "$item" "s@^x \d{4}-\d\d-\d\d @@; s@\s?t:\d{4}-\d\d-\d\d@@;"
